-- MySQL Script generated by MySQL Workbench
-- Fri Jul 28 14:46:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `keyboard` DEFAULT CHARACTER SET utf8 ;


-- Table `keyboard`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `keyboard`.`endereco` (
  `id_endereco` INT AUTO_INCREMENT,
  `cep` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `numero` INT NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` CHAR(2) NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keyboard`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `keyboard`.`usuario` (
  `id_usuario` INT AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `confirmacao_senha` VARCHAR(45) NOT NULL,
  `endereco_id_endereco` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE,
  UNIQUE INDEX `confimacao_senha_UNIQUE` (`confirmacao_senha` ASC) VISIBLE,
  INDEX `fk_usuario_endereco1_idx` (`endereco_id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_endereco1`
    FOREIGN KEY (`endereco_id_endereco`)
    REFERENCES `keyboard`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `keyboard`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `keyboard`.`curso` (
  `id_curso` INT AUTO_INCREMENT,
  `nome_curso` VARCHAR(45) NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB
AUTO_INCREMENT = 100;

-- -----------------------------------------------------
-- Table `keyboard`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `keyboard`.`aula` (
  `id_aula` INT AUTO_INCREMENT,
  `nome_aula` VARCHAR(45) NULL,
  `fk_curso` INT NOT NULL,
  INDEX `fk_dias_has_curso_curso1_idx` (`fk_curso` ASC) VISIBLE,
  PRIMARY KEY (`id_aula`),
  CONSTRAINT `fk_dias_has_curso_curso1`
    FOREIGN KEY (`fk_curso`)
    REFERENCES `keyboard`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `keyboard`.`Questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `keyboard`.`Questao` (
  `idQuestao` INT AUTO_INCREMENT,
  `pergunta` VARCHAR(45) NULL,
  `resposta` VARCHAR(45) NULL,
  `aula_id_aula` INT NOT NULL,
  PRIMARY KEY (`idQuestao`),
  INDEX `fk_Questao_aula1_idx` (`aula_id_aula` ASC) VISIBLE,
  CONSTRAINT `fk_Questao_aula1`
    FOREIGN KEY (`aula_id_aula`)
    REFERENCES `keyboard`.`aula` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO `keyboard`.`curso` (`nome_curso`) VALUES ('Teclado/Piano');
INSERT INTO `keyboard`.`curso` (`nome_curso`) VALUES ('Violão');
INSERT INTO `keyboard`.`curso` (`nome_curso`) VALUES ('Guitarra');
INSERT INTO `keyboard`.`curso` (`nome_curso`) VALUES ('Baixo');
INSERT INTO `keyboard`.`curso` (`nome_curso`) VALUES ('Bateria');

select * from keyboard.curso;

INSERT INTO `keyboard`.`aula` (`nome_aula`, `fk_curso`) VALUES ('Introdução', 100);

select * from keyboard.aula;