-- MySQL Script generated by MySQL Workbench
-- Tue Aug  1 12:37:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema keyboard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadence` DEFAULT CHARACTER SET utf8 ;


-- -----------------------------------------------------
-- Table `cadence`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadence`.`usuario` (
  `id_usuario` INT AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `confirmacao_senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE,
  UNIQUE INDEX `confirmacao_senha_UNIQUE` (`confirmacao_senha` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadence`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadence`.`curso` (
  `id_curso` INT AUTO_INCREMENT,
  `nome_curso` VARCHAR(45) NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB, 
auto_increment = 100;


-- -----------------------------------------------------
-- Table `cadence`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadence`.`aula` (
  `id_aula` INT AUTO_INCREMENT,
  `nome_aula` VARCHAR(45) NULL,
  `fkCurso` INT NOT NULL,
  PRIMARY KEY (`id_aula`),
  INDEX `fk_aula_curso1_idx` (`fkCurso` ASC) VISIBLE,
  CONSTRAINT `fk_aula_curso1`
    FOREIGN KEY (`fkCurso`)
    REFERENCES `cadence`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadence`.`Questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadence`.`Questao` (
  `idQuestao` INT AUTO_INCREMENT,
  `pergunta` VARCHAR(45) NULL,
  `resposta` VARCHAR(45) NULL,
  `fkAula` INT NOT NULL,
  PRIMARY KEY (`idQuestao`),
  INDEX `fk_Questao_aula1_idx` (`fkAula` ASC) VISIBLE,
  CONSTRAINT `fk_Questao_aula1`
    FOREIGN KEY (`fkAula`)
    REFERENCES `cadence`.`aula` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadence`.`AlunoCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadence`.`AlunoCurso` (
  `id` INT AUTO_INCREMENT,
  `fkUsuario` INT NOT NULL,
  `fkCurso` INT NOT NULL,
  INDEX `fk_usuario_has_curso_curso1_idx` (`fkCurso` ASC) VISIBLE,
  INDEX `fk_usuario_has_curso_usuario1_idx` (`fkUsuario` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_has_curso_usuario1`
    FOREIGN KEY (`fkUsuario`)
    REFERENCES `cadence`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_curso_curso1`
    FOREIGN KEY (`fkCurso`)
    REFERENCES `cadence`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cadence`.`AulaAluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cadence`.`AulaAluno` (
  `fkAula` INT NOT NULL,
  `fkAlunoCurso` INT NOT NULL,
  `pontuacao` DECIMAL NULL,
  INDEX `fk_aula_has_AlunoCompleto_AlunoCompleto1_idx` (`fkAlunoCurso` ASC) VISIBLE,
  INDEX `fk_aula_has_AlunoCompleto_aula1_idx` (`fkAula` ASC) VISIBLE,
  CONSTRAINT `fk_aula_has_AlunoCompleto_aula1`
    FOREIGN KEY (`fkAula`)
    REFERENCES `cadence`.`aula` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aula_has_AlunoCompleto_AlunoCompleto1`
    FOREIGN KEY (`fkAlunoCurso`)
    REFERENCES `cadence`.`AlunoCurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `cadence`.`curso` (`nome_curso`) VALUES ('Teclado/Piano');
INSERT INTO `cadence`.`curso` (`nome_curso`) VALUES ('Violão');
INSERT INTO `cadence`.`curso` (`nome_curso`) VALUES ('Guitarra');
INSERT INTO `cadence`.`curso` (`nome_curso`) VALUES ('Baixo');
INSERT INTO `cadence`.`curso` (`nome_curso`) VALUES ('Bateria');

select * from cadence.curso;

INSERT INTO `cadence`.`aula` (`nome_aula`, `fkCurso`) VALUES ('Introdução', 100);

select * from cadence.aula;